export const imagesData = [
  {
    path: '/images/image1.webp',
    dominantColor: '#568aa1',
    id: 1,
    imageName: 'Image Name 1',
  },
  {
    path: '/images/image2.webp',
    dominantColor: '#a67937',
    id: 2,
    imageName: 'Image Name 2',
  },
  {
    path: '/images/image3.webp',
    dominantColor: '#0889c4',
    id: 3,
    imageName: 'Image Name 3',
  },
  {
    path: '/images/image4.webp',
    dominantColor: '#a9a38a',
    id: 4,
    imageName: 'Image Name 4',
  },
  {
    path: '/images/image5.webp',
    dominantColor: '#4185b3',
    id: 5,
    imageName: 'Image Name 5',
  },
  {
    path: '/images/image6.webp',
    dominantColor: '#816a5c',
    id: 6,
    imageName: 'Image Name 6',
  },
  {
    path: '/images/image7.webp',
    dominantColor: '#883e1a',
    id: 7,
    imageName: 'Image Name 7',
  },
  {
    path: '/images/image8.webp',
    dominantColor: '#333b32',
    id: 8,
    imageName: 'Image Name 8',
  },
  {
    path: '/images/image9.webp',
    dominantColor: '#49200e',
    id: 9,
    imageName: 'Image Name 9',
  },
  {
    path: '/images/image10.webp',
    dominantColor: '#a9b6af',
    id: 10,
    imageName: 'Image Name 10',
  },
  {
    path: '/images/image11.webp',
    dominantColor: '#e4c99d',
    id: 11,
    imageName: 'Image Name 11',
  },
  {
    path: '/images/image12.webp',
    dominantColor: '#2d8ee1',
    id: 12,
    imageName: 'Image Name 12',
  },
  {
    path: '/images/image13.webp',
    dominantColor: '#998ead',
    id: 13,
    imageName: 'Image Name 13',
  },
  {
    path: '/images/image14.webp',
    dominantColor: '#062150',
    id: 14,
    imageName: 'Image Name 14',
  },
  {
    path: '/images/image15.webp',
    dominantColor: '#45ade3',
    id: 15,
    imageName: 'Image Name 15',
  },
  {
    path: '/images/image16.webp',
    dominantColor: '#839fa9',
    id: 16,
    imageName: 'Image Name 16',
  },
  {
    path: '/images/image17.webp',
    dominantColor: '#262d34',
    id: 17,
    imageName: 'Image Name 17',
  },
]
